     



     # 4 espaços no começo




server {
    listen 80;
    server_name example.com; # Teste

    location / {
	proxy_pass http://localhost:3000; # Teste
	proxy_set_header Host $host; # Teste
	proxy_set_header X-Real-IP $remote_addr; # Teste
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Teste
	proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# 4 espaços no final





     
