
server {

    server_name tst;

    client_max_body_size 10M;

    root TESTE;

    listen 254.0.0.1:8080;

    error_page 400 123 /pages/custom_errors/400.html;
    error_page 404 /pages/custom_errors/404.html;
}

