# Configuração básica para testar cookies
# Testa cookies habilitados em um location simples

server {
    listen 127.0.0.1:8080;
    server_name localhost;
    
    client_max_body_size 10M;
    
    root ./www;
    
    # Location com cookies habilitados
    location / {
        autoindex on;
        allow_methods GET POST;
        cookies_enabled on;
    }
}

