
server {
    
    # Maximum allowed size for client request bodies
    client_max_body_size 10M;
    # Test para o erro 413 de Payload Too Large
    # client_max_body_size 10B;


    # Server name
    server_name localhost;

    # Listen on port 8080
    listen 127.0.0.1:8080;
    
    # Default error pages
    error_page 400 /error/400.html;
    #error_page 401 /error/401.html;
    #error_page 403 /error/403.html;
    #error_page 404 /error/404.html;
    #error_page 405 /error/405.html;
    #error_page 500 /error/500.html;
    #error_page 501 /error/501.html;
    #error_page 502 /error/502.html;
    #error_page 503 /error/503.html;

    root ./www;

    location /teste/ {
        autoindex on;
        can_upload on;
        alias ./www;
        upload_path ./www/upload;
        index index.html index.htm index.php;
        cgi_extensions .py;
        allow_methods POST DELETE;
    }

    location / {
        autoindex on;
        can_upload on;
        alias ./www;
        upload_path ./www/upload;
        index index.html index.htm index.php;
        cgi_extensions .py;
        allow_methods GET;
    }

    location /upload {
        autoindex on;
        can_upload on;
        alias ./www/upload;
        upload_path ./www/upload;
        index index.html index.htm index.php;
        cgi_extensions .py;
        allow_methods GET POST DELETE;
    }

    location /redirect/ {
        return 301 https://www.google.com;
    }
}