# Configuração simples para testar cookies
# Mínimo necessário para testar funcionalidade básica

server
{
    listen 127.0.0.1:8080;
    server_name localhost;
    
    client_max_body_size 10M;
    
    root ./www;
    
    # Location raiz - cookies habilitados
    location / {
        autoindex on;
        allow_methods GET POST;
        cookies_enabled on;
		}
}
