# Configuração simples para testar cookies
# Mínimo necessário para testar funcionalidade básica

server {
    listen 127.0.0.1:8080;
    server_name localhost;
    
    client_max_body_size 5M;
    
    root ./www;
    
    location / {
        allow_methods GET;
        cookies_enabled on;
    }
}

