server {
	listen 127.0.0.1:8080;

	server_name black;

	root ./www/config-tests/black;

	client_max_body_size 10M;

	error_page 400 /error/400.html;

	location /www/config-tests/black {
		index index.html;
		allow_methods GET;
	}
}

#Ta funcionando, mas nao do jeito que eu pensei que estaria...