server {
	listen 127.0.0.1:8080;

	server_name black;

	root ./www/config-tests/black;

	client_max_body_size 10M;

	error_page 400 /error/400.html;

	location /config-tests/black {
		index index.html;
		allow_methods GET;
	}
}

server {
	listen 127.0.0.10:8081;

	server_name black;

	root ./www/config-tests/white;

	client_max_body_size 10M;

	error_page 400 /error/400.html;

	location /config-tests/white {
		index index.html;
		allow_methods GET;
	}
}

# Se o root estiver sendo usado, em tese, o location block poderia ser assim?
#server {
#	listen 127.0.0.10:8081;
#
#	server_name black;
#
#	root ./www/config-tests/white;
#
#	client_max_body_size 10M;
#
#	error_page 400 /error/400.html;
#
#	location / {			-> Visto que, a raiz que esse servidor considera e o especificado acima
#		index index.html;	-> Entao, o a diretriz location sempre "concatena" a partir do root
#		allow_methods GET;	-> Entendemos dessa forma, mas precisamos confirmar.
#	}
#}
# O nosso servidor ainda nao usa o root pra nada. PRECISAMOS implementar isso!!!!