server {
	listen 127.0.0.10:8080;

	server_name black;

	root ./www/config-tests/black;

	client_max_body_size 10M;

	error_page 400 /error/400.html;

	location /config-tests/black {
		index index.html;
		allow_methods GET;
	}
}

server {
	listen 127.0.0.1:8080;

	server_name white;

	root ./www/config-tests/white;

	client_max_body_size 10M;

	error_page 400 /error/400.html;

	location /config-tests/white {
		index index.html;
		allow_methods GET;
	}
}