server {
	listen 127.0.0.1:8080;

	server_name white;

	root ./www/config-tests/white;

	client_max_body_size 10M;

	error_page 400 /error/400.html;

	location /config-tests/white {
		index index.html;
		allow_methods GET;
	}
}

# O fato do par IP:PORTA ser o mesmo, a gente usa uma hierarquia de leitura. Isto e, o primeiro
# par identificado vai ser o usado. Caso haja outros blocos de server com esse mesmo par, eles
# serao ignorados por virem depois.

# Mas, caso eles tenham outro server_name, isso impacta de alguma forma?
# Nos decidimos isso por algum motivo especifico?
# Acredito que esteja certo mesmo. Pelo fato de so podermos ter 1 socket por par IP:PORTA.

server {
	listen 127.0.0.1:8080;

	server_name black;

	root ./www/config-tests/black;

	client_max_body_size 10M;

	error_page 400 /error/400.html;

	location /config-tests/black {
		index index.html;
		allow_methods GET;
	}
}

# Quando estiver descomentado, o servidor vai startar? Preciso ver com o azevedo essa implementacao
# server {
# 	server_name black;
# 	listen 8080;
# 	host localhost;
# 	root /home/aprado/42Projects/webserv/www/config-tests/black;
# 	index index.html;
# 	client_max_body_size 1M;
# }

# server {
#	listen 127.0.0.1:8080;
#
#	server_name gold;
#
#	root ./www/config-tests/gold;
#
#	client_max_body_size 10M;
#
#	error_page 400 /error/400.html;
#
#	location /config-tests/gold {
#		index index.html;
#		allow_methods GET;
#	}
#}

server {
	listen 127.0.0.1:8080;

	server_name green;

	root ./www/config-tests/green;

	client_max_body_size 10M;

	error_page 400 /error/400.html;

	location /config-tests/green {
		index index.html;
		allow_methods GET;
	}
}

server {
	listen 127.0.0.1:8080;

	server_name gold;

	root ./www/config-tests/gold;

	client_max_body_size 10M;

	error_page 400 /error/400.html;

	location /config-tests/gold {
		index index.html;
		allow_methods GET;
	}
}